// Bring in date/time types and helpers from the `chrono` crate.
//
// DateTime<Utc> is the main timestamp type we use internally.
// TimeZone gives us `Utc.timestamp_opt(...)` for constructing timestamps.
// Utc is the UTC timezone marker.
use chrono::{DateTime, TimeZone, Utc};

// Bring in `clap` derive macros/types.
//
// Parser lets us define command-line arguments using a Rust struct.
// ValueEnum lets us define enums that are valid CLI argument values.
use clap::{Parser, ValueEnum};

// Used so we can call `process::exit(1)` on errors.
use std::process;

/// The unit used for a numeric Unix epoch input.
///
/// Example:
///   1760058546          = seconds
///   1760058546858       = milliseconds
///   1760058546858000    = microseconds
///   1760058546858000000 = nanoseconds
///
/// `ValueEnum` lets clap accept these as command-line values:
///   --unit seconds
///   --unit millis
///   --unit micros
///   --unit nanos
#[derive(Debug, Clone, Copy, ValueEnum)]
enum Unit {
    /// Guess the unit from the number of digits.
    Auto,

    /// Unix epoch seconds.
    Seconds,

    /// Unix epoch milliseconds.
    Millis,

    /// Unix epoch microseconds.
    Micros,

    /// Unix epoch nanoseconds.
    Nanos,
}

/// The output format requested by the user.
///
/// `Output::Auto` means:
///   - if input is numeric epoch, output ISO timestamp
///   - if input is ISO timestamp, output epoch milliseconds
#[derive(Debug, Clone, Copy, ValueEnum)]
enum Output {
    /// Choose a sensible default based on input type.
    Auto,

    /// ISO/RFC3339 timestamp, for example:
    ///   2025-10-10T01:09:06.858Z
    Iso,

    /// Unix epoch seconds.
    Seconds,

    /// Unix epoch milliseconds.
    Millis,

    /// Unix epoch microseconds.
    Micros,

    /// Unix epoch nanoseconds.
    Nanos,
}

/// Command-line arguments for this program.
///
/// `#[derive(Parser)]` tells clap to generate the argument parser from this struct.
///
/// Example usages:
///
///   epochiso 1760058546858
///   epochiso 1760058546
///   epochiso 2025-10-10T01:09:06.858Z
///   epochiso 2025-10-10T01:09:06.858Z --output nanos
///   epochiso 1760058546 --unit seconds
#[derive(Parser, Debug)]
#[command(
    name = "epochiso",
    about = "Convert between Unix epochs and ISO/RFC3339 timestamps"
)]
struct Args {
    /// The one required input value.
    ///
    /// This can be either:
    ///   - a numeric epoch, like 1760058546858
    ///   - an ISO/RFC3339 timestamp, like 2025-10-10T01:09:06.858Z
    value: String,

    /// Input unit for numeric epoch values.
    ///
    /// Defaults to `auto`, which guesses based on digit length.
    ///
    /// Examples:
    ///   1760058546          -> seconds
    ///   1760058546858       -> milliseconds
    ///   1760058546858000    -> microseconds
    ///   1760058546858000000 -> nanoseconds
    #[arg(long, value_enum, default_value_t = Unit::Auto)]
    unit: Unit,

    /// Output format.
    ///
    /// Defaults:
    ///   - numeric epoch input -> ISO timestamp output
    ///   - timestamp input     -> epoch milliseconds output
    #[arg(long, value_enum, default_value_t = Output::Auto)]
    output: Output,

    /// Print debugging info to stderr.
    ///
    /// Example:
    ///   epochiso 1760058546 --verbose
    ///
    /// Might print:
    ///   input kind: epoch
    ///   detected unit: Seconds
    #[arg(short, long, default_value_t = false)]
    verbose: bool,

    /// Treat timestamps without timezone information as UTC.
    ///
    /// RFC3339 timestamps normally include timezone info:
    ///   2025-10-10T01:09:06.858Z
    ///   2025-10-09T18:09:06.858-07:00
    ///
    /// But this program also accepts naive timestamps like:
    ///   2025-10-10 01:09:06.858
    ///
    /// If `assume_utc` is true, those naive timestamps are interpreted as UTC.
    #[arg(long, default_value_t = true)]
    assume_utc: bool,
}

/// Internal classification of the input.
///
/// We use this only to decide what `--output auto` should mean.
#[derive(Debug)]
enum InputKind {
    /// User gave a numeric epoch.
    Epoch,

    /// User gave a timestamp string.
    Timestamp,
}

/// Program entry point.
///
/// Keep `main` small:
///   1. parse CLI args
///   2. call `run`
///   3. print result or error
fn main() {
    // Args::parse() is generated by clap.
    // It reads std::env::args(), validates them, handles --help, etc.
    let args = Args::parse();

    // `run(args)` returns Result<String, String>.
    //
    // Ok(s) means conversion succeeded and `s` is what we should print.
    // Err(e) means conversion failed and `e` is a human-readable error.
    match run(args) {
        Ok(s) => println!("{s}"),
        Err(e) => {
            eprintln!("error: {e}");
            process::exit(1);
        }
    }
}

/// Main program logic.
///
/// This function:
///   1. decides whether the input is numeric or timestamp text
///   2. parses it into DateTime<Utc>
///   3. formats that DateTime into the requested output format
fn run(args: Args) -> Result<String, String> {
    // Remove leading/trailing whitespace from the input.
    let raw = args.value.trim();

    // If the input is all digits, optionally with a leading minus sign,
    // treat it as a Unix epoch.
    if is_integer(raw) {
        // Parse the string into an i128.
        //
        // i128 is larger than we need for normal timestamps, but using it here
        // gives us room to safely multiply seconds/millis/micros into nanoseconds
        // before converting down to the range chrono supports.
        let n: i128 = raw
            .parse()
            .map_err(|_| format!("invalid integer epoch: {raw}"))?;

        // Determine the epoch unit.
        //
        // If the user passed --unit seconds/millis/micros/nanos, use that.
        // Otherwise, guess based on digit length.
        let unit = match args.unit {
            Unit::Auto => detect_epoch_unit(raw),
            explicit => explicit,
        };

        // Optional debugging output.
        //
        // Use stderr so stdout remains machine-friendly.
        if args.verbose {
            eprintln!("input kind: epoch");
            eprintln!("detected unit: {unit:?}");
        }

        // Convert the numeric epoch into our internal representation:
        // DateTime<Utc>.
        let dt = epoch_to_datetime(n, unit)?;

        // Convert DateTime<Utc> to the requested output format.
        format_output(dt, InputKind::Epoch, args.output)
    } else {
        // Non-integer input is treated as a timestamp string.
        //
        // Examples:
        //   2025-10-10T01:09:06.858Z
        //   2025-10-09T18:09:06.858-07:00
        //   2025-10-10 01:09:06.858
        let dt = parse_timestamp(raw, args.assume_utc)?;

        if args.verbose {
            eprintln!("input kind: timestamp");
            eprintln!("parsed UTC: {}", dt.to_rfc3339());
        }

        format_output(dt, InputKind::Timestamp, args.output)
    }
}

/// Return true if a string is an integer.
///
/// Accepted:
///   1760058546
///   -1234567890
///
/// Rejected:
///   1760058546.858
///   2025-10-10T01:09:06Z
///   abc
fn is_integer(s: &str) -> bool {
    // Allow one leading '-' for negative epochs.
    let s = s.strip_prefix('-').unwrap_or(s);

    // After removing a possible minus sign, require at least one digit,
    // and require every character to be an ASCII digit.
    !s.is_empty() && s.chars().all(|c| c.is_ascii_digit())
}

/// Guess epoch unit from number of digits.
///
/// This is a pragmatic heuristic for modern Unix timestamps.
///
/// Current-era examples:
///
///   1760058546          -> 10 digits -> seconds
///   1760058546858       -> 13 digits -> milliseconds
///   1760058546858000    -> 16 digits -> microseconds
///   1760058546858000000 -> 19 digits -> nanoseconds
///
/// This is not mathematically perfect for all historical/future dates.
/// That is why the CLI also supports:
///
///   --unit seconds
///   --unit millis
///   --unit micros
///   --unit nanos
fn detect_epoch_unit(s: &str) -> Unit {
    // Ignore a leading '-' when counting digits.
    let digits = s.strip_prefix('-').unwrap_or(s).len();

    match digits {
        // Treat 10 digits and below as seconds.
        //
        // Example:
        //   1760058546 -> 2025-10-10T01:09:06Z
        0..=10 => Unit::Seconds,

        // Treat 11-13 digits as milliseconds.
        //
        // Example:
        //   1760058546858 -> 2025-10-10T01:09:06.858Z
        11..=13 => Unit::Millis,

        // Treat 14-16 digits as microseconds.
        14..=16 => Unit::Micros,

        // Treat 17+ digits as nanoseconds.
        _ => Unit::Nanos,
    }
}

/// Convert a numeric epoch to DateTime<Utc>.
///
/// Internally this function normalizes everything to:
///
///   total nanoseconds since Unix epoch
///
/// Then it splits that into:
///
///   whole seconds
///   leftover nanoseconds within the second
///
/// chrono wants those two pieces separately:
///
///   Utc.timestamp_opt(seconds, nanos)
fn epoch_to_datetime(value: i128, unit: Unit) -> Result<DateTime<Utc>, String> {
    // Convert the input value into nanoseconds.
    //
    // checked_mul is used so that absurdly large inputs fail cleanly instead
    // of silently overflowing.
    let nanos_total = match unit {
        Unit::Auto => unreachable!("auto should be resolved before epoch_to_datetime"),

        // seconds -> nanoseconds
        Unit::Seconds => value
            .checked_mul(1_000_000_000)
            .ok_or("epoch seconds overflowed nanoseconds")?,

        // milliseconds -> nanoseconds
        Unit::Millis => value
            .checked_mul(1_000_000)
            .ok_or("epoch milliseconds overflowed nanoseconds")?,

        // microseconds -> nanoseconds
        Unit::Micros => value
            .checked_mul(1_000)
            .ok_or("epoch microseconds overflowed nanoseconds")?,

        // already nanoseconds
        Unit::Nanos => value,
    };

    // Split total nanoseconds into seconds plus the nanosecond remainder.
    //
    // We use div_euclid/rem_euclid instead of / and % because they behave
    // better for negative timestamps.
    //
    // Example:
    //   -1 ns should become:
    //     seconds = -1
    //     nanos   = 999_999_999
    //
    // That represents 1969-12-31T23:59:59.999999999Z.
    let secs = nanos_total.div_euclid(1_000_000_000);
    let nanos = nanos_total.rem_euclid(1_000_000_000) as u32;

    // chrono stores seconds as i64.
    // Convert i128 -> i64, failing if the timestamp is too large/small.
    let secs_i64: i64 = secs
        .try_into()
        .map_err(|_| "epoch is outside supported DateTime range")?;

    // Construct DateTime<Utc>.
    //
    // timestamp_opt returns a LocalResult because some timezones have ambiguous
    // or nonexistent local times. UTC does not have daylight saving ambiguity,
    // but this API is still used.
    //
    // `.single()` gives Some(dt) if there is exactly one valid result.
    Utc.timestamp_opt(secs_i64, nanos)
        .single()
        .ok_or_else(|| "epoch is outside supported DateTime range".to_string())
}

/// Parse a timestamp string into DateTime<Utc>.
///
/// Supported forms:
///
///   2025-10-10T01:09:06.858Z
///   2025-10-09T18:09:06.858-07:00
///   2025-10-10 01:09:06.858Z
///   2025-10-10 01:09:06.858-07:00
///   2025-10-10 01:09:06.858     // interpreted as UTC if assume_utc=true
///   2025-10-10T01:09:06.858     // interpreted as UTC if assume_utc=true
fn parse_timestamp(s: &str, assume_utc: bool) -> Result<DateTime<Utc>, String> {
    // First try strict RFC3339.
    //
    // This supports strings like:
    //   2025-10-10T01:09:06.858Z
    //   2025-10-09T18:09:06.858-07:00
    //
    // parse_from_rfc3339 returns DateTime<FixedOffset>, because the input might
    // have an offset like -07:00. We convert it to UTC.
    if let Ok(dt) = DateTime::parse_from_rfc3339(s) {
        return Ok(dt.with_timezone(&Utc));
    }

    // Be a little more forgiving:
    //
    // Some people write timestamps with a space between date and time:
    //   2025-10-10 01:09:06.858Z
    //
    // RFC3339 expects:
    //   2025-10-10T01:09:06.858Z
    //
    // So try replacing spaces with T and parsing again.
    let with_t = s.replace(' ', "T");
    if let Ok(dt) = DateTime::parse_from_rfc3339(&with_t) {
        return Ok(dt.with_timezone(&Utc));
    }

    // If the timestamp has no timezone, optionally treat it as UTC.
    //
    // These are called "naive" datetimes because they do not say what timezone
    // they belong to:
    //
    //   2025-10-10 01:09:06.858
    //   2025-10-10T01:09:06.858
    if assume_utc {
        // Try a handful of common formats.
        //
        // %.f means "optional fractional seconds" in chrono formatting.
        for fmt in [
            "%Y-%m-%d %H:%M:%S%.f",
            "%Y-%m-%dT%H:%M:%S%.f",
            "%Y-%m-%d %H:%M:%S",
            "%Y-%m-%dT%H:%M:%S",
        ] {
            if let Ok(naive) = chrono::NaiveDateTime::parse_from_str(s, fmt) {
                // Attach UTC to the timezone-less datetime.
                return Ok(DateTime::<Utc>::from_naive_utc_and_offset(naive, Utc));
            }
        }
    }

    // If none of the parsing attempts worked, return a user-friendly error.
    Err(format!(
        "could not parse timestamp: {s}. Try RFC3339 like 2025-10-10T01:09:06.858Z"
    ))
}

/// Format DateTime<Utc> according to requested output mode.
///
/// Defaults:
///   - if input was epoch, output ISO
///   - if input was timestamp, output epoch milliseconds
fn format_output(
    dt: DateTime<Utc>,
    input_kind: InputKind,
    output: Output,
) -> Result<String, String> {
    // Resolve Output::Auto to a concrete output mode.
    let output = match output {
        Output::Auto => match input_kind {
            InputKind::Epoch => Output::Iso,
            InputKind::Timestamp => Output::Millis,
        },
        explicit => explicit,
    };

    match output {
        Output::Auto => unreachable!("auto should be resolved before format_output"),

        // Output ISO/RFC3339 with milliseconds.
        //
        // The `true` argument means "use Z instead of +00:00 for UTC".
        //
        // Example:
        //   2025-10-10T01:09:06.858Z
        Output::Iso => Ok(dt.to_rfc3339_opts(chrono::SecondsFormat::Millis, true)),

        // Output epoch seconds.
        Output::Seconds => Ok(dt.timestamp().to_string()),

        // Output epoch milliseconds.
        Output::Millis => Ok(dt.timestamp_millis().to_string()),

        // Output epoch microseconds.
        Output::Micros => Ok(dt.timestamp_micros().to_string()),

        // Output epoch nanoseconds.
        //
        // chrono returns Option here because not every DateTime can be
        // represented as nanoseconds in an i64.
        Output::Nanos => dt
            .timestamp_nanos_opt()
            .map(|n| n.to_string())
            .ok_or_else(|| "timestamp is outside nanosecond output range".to_string()),
    }
}

/// Unit tests.
///
/// Run with:
///
///   cargo test
///
/// These tests protect the important behavior:
///   - digit-length unit detection
///   - seconds vs milliseconds conversion
///   - timestamp parsing with Z and offset timezones
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_integer_accepts_positive_integer() {
        assert!(is_integer("1760058546"));
    }

    #[test]
    fn is_integer_accepts_negative_integer() {
        assert!(is_integer("-1"));
    }

    #[test]
    fn is_integer_rejects_empty_string() {
        assert!(!is_integer(""));
    }

    #[test]
    fn is_integer_rejects_only_minus() {
        assert!(!is_integer("-"));
    }

    #[test]
    fn is_integer_rejects_float() {
        assert!(!is_integer("1760058546.858"));
    }

    #[test]
    fn is_integer_rejects_timestamp() {
        assert!(!is_integer("2025-10-10T01:09:06.858Z"));
    }

    #[test]
    fn detects_seconds_for_10_digits() {
        assert!(matches!(detect_epoch_unit("1760058546"), Unit::Seconds));
    }

    #[test]
    fn detects_seconds_for_negative_10_digits() {
        assert!(matches!(detect_epoch_unit("-1760058546"), Unit::Seconds));
    }

    #[test]
    fn detects_millis_for_13_digits() {
        assert!(matches!(detect_epoch_unit("1760058546858"), Unit::Millis));
    }

    #[test]
    fn detects_micros_for_16_digits() {
        assert!(matches!(
            detect_epoch_unit("1760058546858000"),
            Unit::Micros
        ));
    }

    #[test]
    fn detects_nanos_for_19_digits() {
        assert!(matches!(
            detect_epoch_unit("1760058546858000000"),
            Unit::Nanos
        ));
    }

    #[test]
    fn converts_epoch_seconds_to_datetime() {
        let dt = epoch_to_datetime(1760058546, Unit::Seconds).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
            "2025-10-10T01:09:06.000Z"
        );
    }

    #[test]
    fn converts_epoch_millis_to_datetime() {
        let dt = epoch_to_datetime(1760058546858, Unit::Millis).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
            "2025-10-10T01:09:06.858Z"
        );
    }

    #[test]
    fn converts_epoch_micros_to_datetime() {
        let dt = epoch_to_datetime(1760058546858123, Unit::Micros).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Micros, true),
            "2025-10-10T01:09:06.858123Z"
        );
    }

    #[test]
    fn converts_epoch_nanos_to_datetime() {
        let dt = epoch_to_datetime(1760058546858123456, Unit::Nanos).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Nanos, true),
            "2025-10-10T01:09:06.858123456Z"
        );
    }

    #[test]
    fn converts_zero_epoch_seconds() {
        let dt = epoch_to_datetime(0, Unit::Seconds).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
            "1970-01-01T00:00:00.000Z"
        );
    }

    #[test]
    fn converts_negative_one_second() {
        let dt = epoch_to_datetime(-1, Unit::Seconds).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
            "1969-12-31T23:59:59.000Z"
        );
    }

    #[test]
    fn converts_negative_one_millisecond() {
        let dt = epoch_to_datetime(-1, Unit::Millis).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
            "1969-12-31T23:59:59.999Z"
        );
    }

    #[test]
    fn converts_negative_one_nanosecond() {
        let dt = epoch_to_datetime(-1, Unit::Nanos).unwrap();

        assert_eq!(
            dt.to_rfc3339_opts(chrono::SecondsFormat::Nanos, true),
            "1969-12-31T23:59:59.999999999Z"
        );
    }

    #[test]
    fn parses_rfc3339_z_timestamp() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858Z", true).unwrap();

        assert_eq!(dt.timestamp_millis(), 1760058546858);
    }

    #[test]
    fn parses_rfc3339_offset_timestamp() {
        let dt = parse_timestamp("2025-10-09T18:09:06.858-07:00", true).unwrap();

        assert_eq!(dt.timestamp_millis(), 1760058546858);
    }

    #[test]
    fn parses_rfc3339_with_space_instead_of_t() {
        let dt = parse_timestamp("2025-10-10 01:09:06.858Z", true).unwrap();

        assert_eq!(dt.timestamp_millis(), 1760058546858);
    }

    #[test]
    fn parses_naive_space_timestamp_as_utc_when_enabled() {
        let dt = parse_timestamp("2025-10-10 01:09:06.858", true).unwrap();

        assert_eq!(dt.timestamp_millis(), 1760058546858);
    }

    #[test]
    fn parses_naive_t_timestamp_as_utc_when_enabled() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858", true).unwrap();

        assert_eq!(dt.timestamp_millis(), 1760058546858);
    }

    #[test]
    fn rejects_naive_timestamp_when_assume_utc_disabled() {
        let result = parse_timestamp("2025-10-10 01:09:06.858", false);

        assert!(result.is_err());
    }

    #[test]
    fn rejects_invalid_timestamp() {
        let result = parse_timestamp("not-a-timestamp", true);

        assert!(result.is_err());
    }

    #[test]
    fn formats_datetime_as_iso() {
        let dt = epoch_to_datetime(1760058546858, Unit::Millis).unwrap();

        let output = format_output(dt, InputKind::Epoch, Output::Iso).unwrap();

        assert_eq!(output, "2025-10-10T01:09:06.858Z");
    }

    #[test]
    fn formats_datetime_as_seconds() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858Z", true).unwrap();

        let output = format_output(dt, InputKind::Timestamp, Output::Seconds).unwrap();

        assert_eq!(output, "1760058546");
    }

    #[test]
    fn formats_datetime_as_millis() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858Z", true).unwrap();

        let output = format_output(dt, InputKind::Timestamp, Output::Millis).unwrap();

        assert_eq!(output, "1760058546858");
    }

    #[test]
    fn formats_datetime_as_micros() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858123Z", true).unwrap();

        let output = format_output(dt, InputKind::Timestamp, Output::Micros).unwrap();

        assert_eq!(output, "1760058546858123");
    }

    #[test]
    fn formats_datetime_as_nanos() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858123456Z", true).unwrap();

        let output = format_output(dt, InputKind::Timestamp, Output::Nanos).unwrap();

        assert_eq!(output, "1760058546858123456");
    }

    #[test]
    fn auto_output_for_epoch_is_iso() {
        let dt = epoch_to_datetime(1760058546858, Unit::Millis).unwrap();

        let output = format_output(dt, InputKind::Epoch, Output::Auto).unwrap();

        assert_eq!(output, "2025-10-10T01:09:06.858Z");
    }

    #[test]
    fn auto_output_for_timestamp_is_millis() {
        let dt = parse_timestamp("2025-10-10T01:09:06.858Z", true).unwrap();

        let output = format_output(dt, InputKind::Timestamp, Output::Auto).unwrap();

        assert_eq!(output, "1760058546858");
    }

    #[test]
    fn run_converts_seconds_epoch_to_iso_by_default() {
        let args = Args {
            value: "1760058546".to_string(),
            unit: Unit::Auto,
            output: Output::Auto,
            verbose: false,
            assume_utc: true,
        };

        let output = run(args).unwrap();

        assert_eq!(output, "2025-10-10T01:09:06.000Z");
    }

    #[test]
    fn run_converts_millis_epoch_to_iso_by_default() {
        let args = Args {
            value: "1760058546858".to_string(),
            unit: Unit::Auto,
            output: Output::Auto,
            verbose: false,
            assume_utc: true,
        };

        let output = run(args).unwrap();

        assert_eq!(output, "2025-10-10T01:09:06.858Z");
    }

    #[test]
    fn run_converts_timestamp_to_millis_by_default() {
        let args = Args {
            value: "2025-10-10T01:09:06.858Z".to_string(),
            unit: Unit::Auto,
            output: Output::Auto,
            verbose: false,
            assume_utc: true,
        };

        let output = run(args).unwrap();

        assert_eq!(output, "1760058546858");
    }

    #[test]
    fn run_allows_forced_unit() {
        let args = Args {
            value: "1760058546".to_string(),
            unit: Unit::Millis,
            output: Output::Iso,
            verbose: false,
            assume_utc: true,
        };

        let output = run(args).unwrap();

        assert_eq!(output, "1970-01-21T08:54:18.546Z");
    }

    #[test]
    fn run_allows_forced_output_nanos() {
        let args = Args {
            value: "2025-10-10T01:09:06.858Z".to_string(),
            unit: Unit::Auto,
            output: Output::Nanos,
            verbose: false,
            assume_utc: true,
        };

        let output = run(args).unwrap();

        assert_eq!(output, "1760058546858000000");
    }

    #[test]
    fn run_rejects_bad_input() {
        let args = Args {
            value: "abc123".to_string(),
            unit: Unit::Auto,
            output: Output::Auto,
            verbose: false,
            assume_utc: true,
        };

        let result = run(args);

        assert!(result.is_err());
    }
}
